### ISSUE TITLE
Lyrics overlay

### ISSUE THREAD

**Issue by geecko86** [QuickLyric/QuickLyric#202]
First step will be to get some inspiration from Lyrically and Musixmatch

**Comment by svenoaks** [comment]
Personally I find these overlays horrible to use, I like the notification and click to go to the activity like QuickLyric. It is something to consider that multi-window sort of makes it less desirable to use an overlay, once 7.0+ is popular every phone will have multi-window which gives a better experience than overlay.

**Comment by geecko86** [comment]
I agree, it's not what QuickLyric is about bit there is a high demand for
it. It impacts our ratings and our stats. Business-wise, this is mandatory.

That said, while the competition sucks balls, I do believe it's possible to
make the right choices. Leaving it off by default, making it visually
pleasing, etc.

It's definitely a challenge to not make this sucks balls but I'm sure we
can do it. 🙂

**Comment by geecko86** [comment]
Done! https://twitter.com/QuickLyric/status/884486229470871552
