### ISSUE TITLE
Animating the synchronized lyrics

### ISSUE THREAD

**Issue by geecko86** [QuickLyric/QuickLyric#204]
Something more appealing to the eye, maybe simply a Y Translation and a text appearance fading effect

**Comment by maxlmuller** [comment]
I suggest an animation like the old TTPod Player, with a color "fade out" and "fade in" for the synchronized lyrics. It's really appealing to the eye.
Also, it would be really nice  if there was an karaoke toggle and an option to change the color and size of lyrics. Just like in this video:
https://www.youtube.com/watch?v=JL8FIe8ZEQc
