### ISSUE TITLE
Make it more obvious you can swipe saved lyrics to remove them

### ISSUE THREAD

**Issue by ildar** [QuickLyric/QuickLyric#211]
I like new UI but it seem to have lost the ability to delete saved songs.
I got a really a strange and unrelated text for one song and it irritates me. But I cannot remove it.

**Comment by geecko86** [comment]
You can swipe them, but I agree that it needs to be more obvious.

**Comment by ildar** [comment]
Got tired tapping and long-tapping it :)
thanks!

**Comment by geecko86** [comment]
The rows now have separators (making it more obvious that you can swipe them?) and you can also long-press them.

And yes, I'll push it to Github soon.
