### ISSUE TITLE
Back behavior

### ISSUE THREAD

**Issue by ildar** [QuickLyric/QuickLyric#213]
Back button is a little a annoying when looking through the Saved list. If i choose a song in the list then push Back, the app silently closed. Should bring back to the list.
Thanks

**Comment by geecko86** [comment]
A similar remark was made regarding the search results.

I'm personally happy with the way things are now, but there's a strong possibility that this will end up being modified.

**Comment by geecko86** [comment]
This was fixed a while ago.
