### ISSUE TITLE
Explain why the notification access is necessary

### ISSUE THREAD

**Issue by geecko86** [QuickLyric/QuickLyric#215]
We've been getting a lot of angry reviews lately (possibly from [timusus/Shuttle](https://github.com/timusus/Shuttle)?) that protest that the app is requesting to read their notifications.

The challenge is to express that:

* This permission is called notification access but really we're not going anywhere near their notifications
* The app is open source, transparent and we can prove that nothing shady is going on
* There is no need to leave a 1 star review

Note that even after being explained this, some reviewers continued swearing and said that while this may be true now, it wouldn't be the case once we got bought by.. some rich offshore company.

**Comment by ildar** [comment]
Probably the main concern here is that initially the app demands the
permission while the permission isn't actually critical to the app
execution.
I suggest that initial splash sequence do not demand but softly warn user
about notification access for interfacing some players.
Also probably it is possible to detect if the normal intent mechanism
doesn't work well then ask for the notification access.

**Comment by geecko86** [comment]
It is critical and a solution to this issue was recently implemented. Thanks for reminding me to close it 😉

**Comment by ildar** [comment]
I guess you mean this:
https://github.com/QuickLyric/QuickLyric/commit/bc77d13598cf67ee6f0f35e87b562a4d8bb9819c
Unfortunately the commit message doesn't explain much. Maybe that's why I
don't see any good in this commit besides the author doesn't have to catch
up all music players in the hood.
BTW, you forgot to tag the last release. (→ I didn't receive it through
F-Droid)
Thanks!

**Comment by geecko86** [comment]
No that's not what I meant. And yes it's not on GitHub yet.

**Comment by ildar** [comment]
I see that GitHub source and tags desperately outdated. Would you please
push commits and tags please? I'm using F-Droid version and so don't see
recent changes.
Thanks in advance!

**Comment by geecko86** [comment]
Soon enough. F-Droid is honestly our lowest priority, I'm sure you understand that.

**Comment by ildar** [comment]
Actually, no, I don't. One month I hoped something to clear up but it
didn't. Now could you please clarify:
1. When the latest commits appear in github?
2. Will the app continue being open source?
3. What's wrong with F-Droid?

**Comment by geecko86** [comment]
It is open source, except when it's not possible to implement a feature (i.e. MusicID via ACRCloud) through OSS libraries.

You need money to run a startup, F-Droid does not help towards that goal. We have no good reason to prioritize F-Droid. It simply isn't important. It's not behind the Play Store version, if that's what you're wondering.

**Comment by geecko86** [comment]
We switched from pushing new features as they are implemented to pushing big updates with tons of new features & bug fixes. Hence what appears as a slower pace.

**Comment by ildar** [comment]
I got it about your priorities now. And I'm really happy that the app
remains open source.
Still i don't see the latest commits. When then?
About new features involving closed source libs: if I got you right, you
add some of those incompatible with F-Droid additions, right? Then ideally
there could be a gradle switch that turns it off for pure FOSS builds, if
you please.
I hope that my suggestion wont offend you in any way. Thank you.
