### ISSUE TITLE
Use queue for lyrics retrieval

### ISSUE THREAD

**Issue by svenoaks** [QuickLyric/QuickLyric#220]
The lyrics retrieval for anything that will update LyricsViewFragment should be in queue of some type, loose `DownloadThread` can cause race conditions.

One easy way to demonstrate is turn on 'Automatically Refresh Lyrics' place

`private static long delay = 25000;`

in DownloadThread

and

```
delay -= 5000;
if (delay < 0) delay = 0;
try {
     Thread.sleep(delay);
} catch (InterruptedException e) {
      e.printStackTrace();
}
```
in beginning of run().

Start program and skip tracks repeatedly from the notification drawer. You will get it turning the LyricsViewFragment to the earlier ones after the later. This kind of thing not unlikely with spotty network access and more likely to happen (and more annoying) with recent tracks addition.

There should be a single queue for retrieving the lyrics from refreshing and recent tracks. I wouldn't trust the http connections to ever return even with a timeout unless I was really familiar with it, I'd have a way to basically abandon the threads and ignore callbacks after my own timeout, otherwise you could get in situation where it simply not refresh anymore, unless the app was force stopped.

**Comment by geecko86** [comment]
Can we close this?
