### ISSUE TITLE
Allow to choose which app to take the current song from or to ignore certain apps

### ISSUE THREAD

**Issue by MissingNoIOI** [QuickLyric/QuickLyric#225]
Right now I have the problem that QuickLyric searches for the active audiobook in the Audible app, even when there's actually another app running or if close the Audible notification or force stop it. The only way to get the lyrics from another song is completely restarting my phone. It's a Huawei Note 9 with Emui 5.0 (Android 7.0)

**Comment by geecko86** [comment]
So you're actively listening to a song in another app but it still detects the audiobook?

Which build are you running? Do you see a difference between the build on F-Droid and the one on Google Play?

**Comment by geecko86** [comment]
This bug has been fixed. Thank you for your feedback. It will be up soon on Github and is already available on Play in Beta.
