### ISSUE TITLE
Mismatched API level checking in SettingsActivity and SearchActivity

### ISSUE THREAD

**Issue by frankFic** [QuickLyric/QuickLyric#230]
Hi,

I just found that in SettingsActivity and SearchActivity there are invocations of getWindow().setStatusBarColor() with mismatched API level checking.
The API is introduced in API level 21 but the conditions indicated that in these two activities, the API can be called on API 20. (In AboutActivity the checking is correct)

There are similar problems when calling setNavigationBarColor() in SearchActivity.

Thx.

**Comment by geecko86** [comment]
Does API 20 actually exist in the wild? Are there people who have it on
their device?

**Comment by ildar** [comment]
I think not.
https://en.wikipedia.org/wiki/Android_(operating_system)#Platform_usage
