### ISSUE TITLE
3 questions

### ISSUE THREAD

**Issue by FixxeS** [QuickLyric/QuickLyric#232]
Why some songs have like a karaoke like system and some others don't?
Also, where does quickLyric fetches the lyrics? I would like to add my own lyrics, I have songs from independent artists and less known songs, specially remixes, so I would like to make them available on a website where quickLyric fetches lyrics, so that the lyrics could be available not only on that website, but as a consequence of that also available on quickLyric. I read the readme but found no information about that.
Third questions is, how do I use batch download? I didn't found how.

Thanks in advance.

**Comment by geecko86** [comment]
1. We don't have the timecodes for all songs.
2. If you use the code from GitHub, you can find a list [here](https://github.com/QuickLyric/QuickLyric/tree/master/QuickLyric/src/main/java/com/geecko/QuickLyric/provider). If you use the one that's on the play store, it's our own catalog. We'll have much to announce in that regards soon.
3. It's in the saved lyrics screen, top right corner.
