### ISSUE TITLE
Download the lyrics before the overlay is even opened

### ISSUE THREAD

**Issue by FixxeS** [QuickLyric/QuickLyric#233]
I would like to suggest the following:
Make like an option on quickLyric to open itself in background when a music app is opened and that closes itself when a compatible music app is closed. Adding to that, the app could fetch the lyrics automatically (without the user clicking the overlay button) so they would be already ready to read. Of course, making it a switch or a check on the settings because of small data plans, so when you install the app its disabled by default. 
This would require a permission to use WiFi and data in background I think, so to don't alarm people that permission acceptance could be triggered when the option is turned on, so users would know why the app is requesting that permission (because of those folks that think that the app is gonna steal information or something because of the internet usage allowance).
Also, and this is like a feature I would love, is, if there's no lyric, the app wouldn't show the overlay button on top of music playing app.
To make the app able to start and stop when a compatible music player is opened and closed, I think that would require like a monitoring service or process that starts with the system on boot. Another permission I think.

I think it would be great to do have that, I think it would turn the app much more easy to use and user friendly, specially if you introduce the automatic online search and not showing the button if there's no lyrics.

I have some very very creative ideas sometimes but I don't even know if all of this is possible, so all I wish is that this helps in future development in some way :)

**Comment by geecko86** [comment]
This is now the case, at least with the build that's on the play store.

Sources will be uploaded soon enough.
