### ISSUE TITLE
Save searched Songname with the filename

### ISSUE THREAD

**Issue by Thomas131** [QuickLyric/QuickLyric#239]
Hello!
I just downloaded the app 1/2 hour ago and it is great!

One thing I would really like would be that the app remembers which String I searched for while playing a song ...

My songs are all not tagged. If I play a song, it searches for the filename (for sure, it doesn't have additional info). But when I change the query, it could save my query alongside with the filepath so that it could just display the lyrics I searched for the last time.

Best regards!
Thomas

**Comment by geecko86** [comment]
> My songs are all not tagged

This is the real issue.

Either tag your songs (there are tools to tag all of them at once) or get the app from the play store. The build that's on the play store doesn't require tags, since it can fingerprint audio files.
