### ISSUE TITLE
Sending Strings from another app doesn't work

### ISSUE THREAD

**Issue by svenoaks** [QuickLyric/QuickLyric#240]
If you use
`startActivity(new Intent("com.geecko.QuickLyric.getLyrics").putExtra("TAGS", new String[]{"Daft Punk", "Get Lucky"}));`

QuickLyric will not necessarily open the Daft Punk song, it will open the currently playing or last played song.

1. Open player in Shuttle.
2. Play song in Google Play Music from the notification
3. Hit Lyric button in Shuttle
4. QuickLyric button will open the Google Play Music song

Strings are sent but not used.

**Comment by geecko86** [comment]
Hey Steve how've you been?

I was not able to reproduce this. Which build did you use?

PS: I will update the repo this week.

**Comment by svenoaks** [comment]
Good, looking forward to winter break and then working on QL.

Here is video with current Google Play version:

[https://drive.google.com/file/d/1iW8-_at-X-TZfPV5dy8NL5ag6aJ0ni9n/view?usp=sharing](https://drive.google.com/file/d/1iW8-_at-X-TZfPV5dy8NL5ag6aJ0ni9n/view?usp=sharing)

Should show Lorde song all three times.

Can you email me link to use for my app to link to QL, as you say you want to use a Firebase link?

**Comment by geecko86** [comment]
Thanks for the video. Seems like the issue only occurs when the activity is created and the metadata is read from the intent at that point.

There might also be a race condition somewhere, since I can't reproduce this even when the activity is already created.

Will send you a link!

**Comment by svenoaks** [comment]
Some kind of race condition, sometimes it works and sometimes it doesn't.

Always `update()` is called on the requested song from another app, then update() again called on currently playing song. Sometimes there is an additional call to update with the song requested from other app from 

https://github.com/QuickLyric/QuickLyric-Play/blob/923d63e97019a32331c917b26294160e9b332999/QuickLyric/src/main/java/com/geecko/QuickLyric/fragment/LyricsViewFragment.java#L1570

which is only way the correct lyrics get displayed.

**Comment by svenoaks** [comment]
I think change 
https://github.com/QuickLyric/QuickLyric-Play/blob/923d63e97019a32331c917b26294160e9b332999/QuickLyric/src/main/java/com/geecko/QuickLyric/fragment/LyricsViewFragment.java#L1612
to
`&& lrcView[0].getVisibility() == View.VISIBLE && !manualUpdateLock) {`
will fix it. The currently playing song is incorrectly displayed through this line as it is.

**Comment by geecko86** [comment]
It's getting late over here, I'll take a look at it tomorrow.

If it makes sense to you (and doesn't seem like a random quick fix) & you've done sufficient testing, never hesitate to commit it and to push it.
