### ISSUE TITLE
LOGO

### ISSUE THREAD

**Issue by ghost** [QuickLyric/QuickLyric#242]
Hello, @geecko86 I want to contribute in "QuickLyric" so i  want to design a new logo for "QuickLyric" and it's free.

I hope you like it. If you like it, I will send you to pull request, editable files/original source and .png format files. If there's something you want to change, I'll do it.

if you want i will send you my design

**Comment by geecko86** [comment]
Hey there. Thanks for the offer! You can find our email address on [the website](https://www.quicklyric.be) and send us what you made over there. We can't really have a discussion before we've seen it..

Also, we're kind of perfectly happy with our current logo, for what it's worth. Maybe show us what you've done before and convince us that we need to change logos?

**Comment by ghost** [comment]
Hello sir i can see your logo is too old and that's why i suggest you for new logo here some logo if you choose any one i can change in it and i will send you original editable files 

![11 copy](https://user-images.githubusercontent.com/38813945/39835076-6d167c34-53e8-11e8-8057-f3f914ca3381.png)

**Comment by geecko86** [comment]
I'ma fraid we're gonna have to pass on your offer. Thanks for your efforts!
