### ISSUE TITLE
i will love to do copywriting for you 

### ISSUE THREAD

**Issue by hamzeyto** [QuickLyric/QuickLyric#243]
I love your application and would want to contribute to it, I'm not a developer but I am good at copywriting. I would love to make a copywrite for your Readme and make a pull request for you to merge. Your response would be highly appreciated. Also I would like to request if we could communicate either here or via email, so I don't have to create issues. Thank you.

**Comment by geecko86** [comment]
Hey Hamzeto,

Thanks for the offer!

Why don't you take a look at the Play Store description and tell us if you can come up with something better? I'm sure there's room for improvement.

https://play.google.com/store/apps/details?id=com.geecko.QuickLyric
