### ISSUE TITLE
Add support for NewPipe

### ISSUE THREAD

**Issue by 3demax** [QuickLyric/QuickLyric#244]
Hi! First of all thanks for the great app and making it open source!

[New Pipe](https://newpipe.schabi.org) is a great open source YouTube player, and makes it easy to listen to music playlists.
Would you consider adding support for that player? If you do, that would be great!

**Comment by geecko86** [comment]
Thanks! I use Newpipe myself. 

I guess I can give it a shot, but the thing about youtube is that it doesn't have proper metadata (artist & title) ; it only provides the video title. This makes it a bit of a hack. 

QuickLyric actually uses the NewPipe library for some of that stuff.
https://github.com/QuickLyric/QuickLyric/blob/9847aa13ad4c4ee07d1dc13b5bde7892ac0716c5/QuickLyric/build.gradle#L134

**Comment by geecko86** [comment]
@3demax Alright, seems to work. It will be up on Google Play ASAP, and on GitHub later.

![test](https://dl2.pushbulletusercontent.com/F3DGgnQyeDvNneu4kdywmZCmskIMdDv6/Screenshot_NewPipe_20180714-024154.png)

Feel free to re-open if you notice any issue.

**Comment by StefanBrand** [comment]
Cannot get automatic lyrics fir this video: Cornerstone - Hillsong Worship - https://www.youtube.com/watch?v=izrk-erhDdk on Android Kitkat 4.4.2
