### ISSUE TITLE
Missing feature: floating lyrics (Android lollipop)

### ISSUE THREAD

**Issue by bengaskin** [QuickLyric/QuickLyric#247]
Has this feature been implemented? It was in the fdroid description, but it doesn't work for me and I can't even see any settings/menu option to turn this on or off.

**Comment by geecko86** [comment]
We no longer upload builds to F-Droid for a bunch of reasons, sorry..
Floating lyrics have been here for over a year.

**Comment by bengaskin** [comment]
Actually i got it from the play store, after first going to fdroid.

It seems that the play store also similarly misrepresents the features.

This app doesn't float in any way as far as I can see. Android Galaxy s6
edge lollipop.

Not sure where you want to log the bug / feature incompleteness. Or if
there are additional Android version requirements.

So,... Just letting you know.

I'm not sure what else I'm supposed to do aside from maybe leaving a bad
review on the app.

I'd be happy with the app on its own merits if it doesn't try to claim to
do more.

Ideally I really was looking for a floating app. That would be best, and
that was the key word that led me to the app to begin with.

**Comment by geecko86** [comment]
> I'm not sure what else I'm supposed to do aside from maybe leaving a bad review on the app.

Getting in touch with directly with the devs is always the best approach.

This is what the floating lyrics look like:

http://quicklyric.be/images/screenshots/3.jpg

Something close to what you would see with Facebook Messenger for instance, when using Chat Heads.

You can enable them in the settings and the little red bubble should pop up when the lyrics are available. In order to avoid bothering the user, it will not appear if the lyrics are not available.

**Comment by bengaskin** [comment]
Okay I'll try and figure out what's going and get back to you guys through
the proper channels. For now it looks like I had indeed installed through
fdroid but Google play was aware of it, I mistakenly thought it was from
Google play.

After a bit of uninstalling and reinstalling, I believe the version on
Google play is slightly buggy in some scenarios but does indeed (in optimal
conditions) work with a floating overlay.

Still, something doesn't look right on fdroid.

If it's gpl software, why is the older version on fdroid but with the
description of the newer version?

This is just me thinking out loud

I'll clarify my thoughts and come back to this.

**Comment by geecko86** [comment]
> If it's gpl software, why is the older version on fdroid but with the
description of the newer version?

I'm... Not sure. I don't remember editing the description on F-Droid, and it definitely could not have been someone else on the team. Maybe an external contribution? I really think that's the only valid explanation.

> Google play is slightly buggy in some scenarios but does indeed (in optimal conditions) work with a floating overlay.

Would love to hear more about these bugs you mentioned.
