### ISSUE TITLE
Ads break this app

### ISSUE THREAD

**Issue by quietmansoath** [QuickLyric/QuickLyric#248]
If you're going to charge now for an app that you [originally gloated](https://www.reddit.com/r/Android/comments/2x9kwd/dev_quicklyric_my_free_adfree_convenient_lyrics/) about [being free](https://www.reddit.com/r/Android/comments/5ygip4/appdev_quicklyric_my_free_open_source_material/), at least make the ads unobtrusive.

I've used this app from Android 8.0 to 8.1 to Pie and back again, and half the time the ads block or partially hide the refresh button. Then, the ads will reload mid-song and jump the screen all the way back to the top, making me lose my place.

Also, I would have totally considered buying the app if there was a one-time/lifetime purchase, as I get it costs you time to make it, but a subscription for a _lyrics_ app? That just seems like a little too much. 3rd party twitter apps, Titanium Backup, and podcast apps like Pocket Caster offer much more value and don't charge subscriptions. They aren't even $8. $10/year for this app is crazy. Please reconsider.

**Comment by geecko86** [comment]
This issue tracker is not suited for the commercial aspects of QuickLyric, please email us at contact@quicklyric.be.
