### ISSUE TITLE
Automatic lyrics translation to preferred language

### ISSUE THREAD

**Issue by marcoscmonteiro** [QuickLyric/QuickLyric#261]
Implement an way (user optional) to automaticaly translate lyrics to a preferred language of user choice using a translation provider like Google Translate for example. Default can be the android user language. Its interesting if translated text can be viewed in parallel with original lyrics text.

**Comment by geecko86** [comment]
Those APIs are expensive and don't work all that well when it comes to song lyrics.

Not to say providing translations won't happen - in fact I'm looking into the best way of handling this - but it definitely won't happen through machine translation.
