### ISSUE TITLE
"Unable to connect" issue

### ISSUE THREAD

**Issue by swchrrnote** [QuickLyric/QuickLyric#277]
Hello all,

After much deliberation and action, I have finally managed to solve this issue at last. It turns out, the keys that the developer has used have expired or are simply not working anymore. For the past hour, I have been busy attempting to compile a new apk with my own keys, which you can now find on my own fork page of this repository over at https://github.com/swchrrnote/QuickLyric/releases/tag/Latest

The only changes made to the final binary was the changing of the keys. The source code in the new repository is unmodified, so unless you want to switch it out for your own keys, do not bother compiling from mine.

**Comment by russianspy1234** [comment]
Android 13 won't allow giving the notification access to side loaded apps. Can you upload to fdroid so the privileged extension can be used?

**Comment by RokeJulianLockhart** [comment]
@russianspy1234, that might be better reported at the linked repository.

**Comment by RokeJulianLockhart** [comment]
@geecko86, if this isn't fixed, the application is useless. Why close the issue?

**Comment by swchrrnote** [comment]
I suppose it's because the developer doesn't plan to fix it. It's unfortunate as it's not a difficult fix. As for my own repo, I'll see if I can redo it to contain instructions on changing the Genius keys.

There are other things that are broken in the app right now that, thanks to my lack of coding skills, only a proper developer such as @geecko86 could fix but for now, it seems like QuickLyric can be considered as abandonware. RIP
